# Generated by Django 6.0.1 on 2026-04-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncentivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('fixed_base_amount', models.FloatField()),
                ('variable_base_amount', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('PER', 'Percentage'), ('RAT', 'Rating'), ('AMT', 'Amount')], max_length=3)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('aggr_method', models.CharField(choices=[('AVG', 'Average'), ('SUM', 'Total'), ('MIN', 'Minimum'), ('MAX', 'Maximum')], default='AVG', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.context')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.metric')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.metric')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.incentiveplan')),
            ],
        ),
        migrations.CreateModel(
            name='IncentiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('amount', models.FloatField()),
                ('attempt_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_breakdown', models.JSONField(default=dict)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.context')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.incentiveplan')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'plan', 'context', 'attempt_number'), name='unique_attribute_number')],
            },
        ),
    ]
